import { validateEnv } from '../config/env.js';

// Validate environment variables at module load
const env = validateEnv();

export const constants = {
  MONGODB_URI: env.MONGODB_URI,
  MONGODB_NAME_DATABASE: env.MONGODB_NAME_DATABASE,
  BETTER_AUTH_SECRET: env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: env.BETTER_AUTH_URL,
  CIRCLE_KIT_KEY: env.CIRCLE_KIT_KEY,
  CIRCLE_API_KEY: env.CIRCLE_API_KEY,
  CIRCLE_ENTITY_SECRET: env.CIRCLE_ENTITY_SECRET,
  CIRCLE_WALLET_SET_ID: env.CIRCLE_WALLET_SET_ID,
  TWITTER_CLIENT_ID: env.TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: env.TWITTER_CLIENT_SECRET,
  TWITTER_CONSUMER_KEY: env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN: env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET: env.TWITTER_ACCESS_SECRET,
  LLM_API_KEY: env.LLM_API_KEY,
  LLM_MODEL: env.LLM_MODEL,
  PRIVY_APP_ID: env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: env.PRIVY_APP_SECRET,
  PORT: env.PORT,
  FRONTEND_URL: env.FRONTEND_URL,
  GOOGLE_CLIENT_ID: env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: env.GOOGLE_CLIENT_SECRET,
  RESEND_API_KEY: env.RESEND_API_KEY,
};