import { validateEnv } from '../config/env.js';

// Validate environment variables at module load
const env = validateEnv();

export const constants = {
  MONGODB_URI: env.MONGODB_URI,
  MONGODB_NAME_DATABASE: env.MONGODB_NAME_DATABASE,

  BETTER_AUTH_SECRET: env.BETTER_AUTH_SECRET,

  TWITTER_CLIENT_ID: env.TWITTER_CLIENT_ID,
  TWITTER_CLIENT_SECRET: env.TWITTER_CLIENT_SECRET,
  TWITTER_CONSUMER_KEY: env.TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET: env.TWITTER_CONSUMER_SECRET,
  TWITTER_ACCESS_TOKEN: env.TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET: env.TWITTER_ACCESS_SECRET,

  LLM_API_KEY: env.LLM_API_KEY,
  LLM_MODEL: env.LLM_MODEL,

  PRIVY_APP_ID: env.PRIVY_APP_ID,
  PRIVY_APP_SECRET: env.PRIVY_APP_SECRET,

  PORT: env.PORT,
  FRONTEND_URL: env.FRONTEND_URL,
};